steps:
  - name: gcr.io/cloud-builders/docker
    id: build-docker-image
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
      - --cache-from
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest
      - .
  - name: gcr.io/cloud-builders/docker
    id: push-docker-image
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-cloud-run
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image
      - gcr.io/$PROJECT_ID/${_SERVICE_NAME}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --update-env-vars
      - GCP_PROJECT=$_GCP_PROJECT
      - --update-env-vars
      - CLOUD_SQL_CONNECTION_NAME=$_CLOUD_SQL_CONNECTION_NAME
      - --update-env-vars
      - DB_USERNAME=$_DB_USERNAME
      - --update-env-vars
      - DB_PASSWORD=$_DB_PASSWORD
      - --update-env-vars
      - DB_DATABASE=$_DB_DATABASE
substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: ''
  _GCP_PROJECT: ''
  _CLOUD_SQL_CONNECTION_NAME: ''
  _DB_USERNAME: ''
  _DB_PASSWORD: ''
  _DB_DATABASE: ''
images:
  - gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest