// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Todo   string `json:"todo"`
	UserID int    `json:"userId"`
}

type CreateUserInput struct {
	Name string `json:"name"`
}

type UpdateUserInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}
