// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTodoInput struct {
	Todo   string `json:"todo"`
	UserID int    `json:"userId"`
}

type CreateUserInput struct {
	Name string `json:"name"`
}

type DeleteTodoInput struct {
	ID int `json:"id"`
}

type DeleteUserInput struct {
	ID int `json:"id"`
}

type UpdateTodoInput struct {
	ID       int    `json:"id"`
	Todo     string `json:"todo"`
	Finished bool   `json:"finished"`
	UserID   int    `json:"userId"`
}

type UpdateUserInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserFilter struct {
	Name *string `json:"name"`
}
